version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Current IAM identity:"
      - aws sts get-caller-identity
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Building function package..."
      - zip -r function.zip .
      - echo "Uploading to S3..."
      - aws s3 cp function.zip "s3://$ARTIFACT_BUCKET/$LAMBDA_NAME/function-$(date +%Y%m%d%H%M%S).zip"
      - sleep 10
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name $LAMBDA_NAME --s3-bucket $ARTIFACT_BUCKET --s3-key "$LAMBDA_NAME/function-$(date +%Y%m%d%H%M%S).zip"
artifacts:
  files:
    - 'function.zip'

