version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .

  build:
    commands:
      - echo "Packaging Lambda function..."
      - TIMESTAMP=$(date +%Y%m%d%H%M%S)
      - ZIP_FILE="function-${TIMESTAMP}.zip"
      - zip -r ${ZIP_FILE} .
      - echo "Uploading to S3..."
      - aws s3 cp ${ZIP_FILE} s3://${ARTIFACT_BUCKET}/${LAMBDA_NAME}/${ZIP_FILE}
      - echo "Updating Lambda..."
      - aws lambda update-function-code --function-name ${LAMBDA_NAME} --s3-bucket ${ARTIFACT_BUCKET} --s3-key "${LAMBDA_NAME}/${ZIP_FILE}"
      - echo "Done."

artifacts:
  files:
    - '*.zip'
