version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - zip function.zip app.py
      - aws s3 cp function.zip s3://your-s3-bucket-name/function.zip
      - aws lambda update-function-code \
          --function-name your-lambda-function-name \
          --s3-bucket your-s3-bucket-name \
          --s3-key function.zip

artifacts:
  files:
    - function.zip
