version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 3.8  
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt  

  build:
    commands:
      - echo "Building the Lambda function..."
      - zip -r function.zip . -x "*.git*" -x "buildspec.yml"

artifacts:
  files:
    - function.zip