version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Building Lambda package..."
      - zip -r function.zip . -x "*.git*" -x "buildspec.yml"
      - zip -r function.zip handler.py *.py  # Explicitly include handler
      - zip -r function.zip -x "*.git*" -x "test_*.py"  # Exclude test files
      - ls -lh function.zip

  post_build:
    commands:
      - echo "Build ID: ${CODEBUILD_BUILD_ID}"
      - echo "Attempting to update Lambda..."
      - aws lambda update-function-code --function-name lambdaforcicd --s3-bucket bucketforcicdpipe --s3-key function-${CODEBUILD_BUILD_ID}.zip --region us-east-1
      - echo "Exit code: $?"

artifacts:
  files:
    - function.zip
