version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Building Lambda package..."
      - zip -r function.zip handler.py *.py
      - zip -r function.zip -x "*.git*" -x "test_*" -x "buildspec.yml"
      - ls -lh function.zip

  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp function.zip s3://bucketforcicdpipe/function-${CODEBUILD_BUILD_ID}.zip
      - echo "Updating Lambda..."
      - aws lambda update-function-code --function-name lambdaforcicd --s3-bucket bucketforcicdpipe --s3-key function-${CODEBUILD_BUILD_ID}.zip --region us-east-1

artifacts:
  files:
    - function.zip
